# Generated by Django 5.0.6 on 2024-06-02 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='nombre_completo',
            field=models.CharField(max_length=255),
        ),
    ]
