# Generated by Django 5.0.6 on 2024-06-07 00:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_producto_tipdecuidado_veterinaria_citamedica"),
    ]

    operations = [
        migrations.AddField(
            model_name="citamedica",
            name="user",
            field=models.ForeignKey(
                default=4,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
